# Generated by Django 2.2.19 on 2021-04-02 12:03

from django.db import migrations, models


def forward(apps, schema_editor):
    AgendaFilterTypeName = apps.get_model('name', 'AgendaFilterTypeName')
    names = (
        ('none', 'None', 'Not used except for a timeslot-type column (e.g., officehours)'),
        ('normal', 'Normal', 'Non-heading filter button'),
        ('heading', 'Heading', 'Column heading button'),
        ('special', 'Special', 'Button in the catch-all column'),
    )
    for order, (slug, name, desc) in enumerate(names):
        AgendaFilterTypeName.objects.create(slug=slug, name=name, desc=desc, order=order, used=True)


def reverse(apps, schema_editor):
    pass  # nothing to do, model about to be destroyed anyway


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0027_add_bofrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaFilterTypeName',
            fields=[
                ('slug', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('used', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.RunPython(forward, reverse),
    ]
