# Copyright The IETF Trust 2021 All Rights Reserved

# Generated by Django 2.2.24 on 2021-07-26 16:55

from django.db import migrations


def forward(apps, schema_editor):
    ProceedingsMaterialTypeName = apps.get_model('name', 'ProceedingsMaterialTypeName')
    names = [
        {'slug': 'social_event', 'name': 'Social Event', 'desc': 'Social event'},
        {'slug': 'host_speaker_series', 'name': 'Host Speaker Series', 'desc': 'Host speaker series'},
        {'slug': 'acknowledgements', 'name': 'Acknowledgements', 'desc': 'Acknowledgements'},
        {'slug': 'additional_information', 'name': 'Additional Information', 'desc': 'Any other materials'},
    ]
    for name in names:
        ProceedingsMaterialTypeName.objects.create(used=True, **name)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0030_proceedingsmaterialtypename'),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
