# Copyright The IETF Trust 2021 All Rights Reserved

# Generated by Django 2.2.24 on 2021-09-16 09:42

from django.db import migrations


def forward(apps, schema_editor):
    SessionPurposeName = apps.get_model('name', 'SessionPurposeName')
    TimeSlotTypeName = apps.get_model('name', 'TimeSlotTypeName')

    for order, (slug, name, desc, tstypes) in enumerate((
            ('session', 'Session', 'Group session', ['regular']),
            ('tutorial', 'Tutorial', 'Tutorial or training session', ['other']),
            ('officehours', 'Office hours', 'Office hours session', ['other']),
            ('coding', 'Coding', 'Coding session', ['other']),
            ('admin', 'Administrative', 'Meeting administration', ['other', 'reg']),
            ('social', 'Social', 'Social event or activity', ['other']),
            ('presentation', 'Presentation', 'Presentation session', ['other', 'regular'])
    )):
        spn = SessionPurposeName.objects.create(
            slug=slug,
            name=name,
            desc=desc,
            used=True,
            order=order,
        )
        for ts_type in tstypes:
            spn.timeslot_types.add(TimeSlotTypeName.objects.get(pk=ts_type))


def reverse(apps, schema_editor):
    SessionPurposeName = apps.get_model('name', 'SessionPurposeName')
    SessionPurposeName.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0035_sessionpurposename'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
