version: '3.8'

services:
    app:
        environment:
            EDITOR_VSCODE: 1
            DJANGO_SETTINGS_MODULE: settings_local_sqlitetest
        volumes:
            - ..:/root/src
        # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
        network_mode: service:db