# Generated by Django 2.2.24 on 2021-09-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0036_populate_sessionpurposename'),
        ('group', '0050_populate_groupfeatures_agenda_filter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupfeatures',
            name='session_purposes',
            field=models.ManyToManyField(help_text='Allowed session purposes for this group type', to='name.SessionPurposeName'),
        ),
    ]
