# Copyright The IETF Trust 2021 All Rights Reserved

# Generated by Django 2.2.24 on 2021-09-26 11:29

from django.db import migrations


default_purposes = dict(
    dir=['presentation', 'social', 'tutorial'],
    ietf=['admin', 'presentation', 'social'],
    rg=['session'],
    team=['coding', 'presentation', 'social', 'tutorial'],
    wg=['session'],
)


def forward(apps, schema_editor):
    GroupFeatures = apps.get_model('group', 'GroupFeatures')
    SessionPurposeName = apps.get_model('name', 'SessionPurposeName')
    for type_, purposes in default_purposes.items():
        gf = GroupFeatures.objects.get(type=type_)
        for purpose in purposes:
            gf.session_purposes.add(SessionPurposeName.objects.get(pk=purpose))

def reverse(apps, schema_editor):
    GroupFeatures = apps.get_model('group', 'GroupFeatures')
    for gf in GroupFeatures.objects.all():
        gf.session_purposes.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0051_groupfeatures_session_purposes'),
        ('name', '0036_populate_sessionpurposename'),

    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
